### PR TITLE
fix optomal7 told me about

### PR DESCRIPTION
**Pull request by jaredatron**

### CODE REVIEW

**Comment by jaredatron** [comment]
@optomal7 please leave a comment explaining this change here :)

@tannerwelsh please check this out!

**Comment by optomal7** [comment]
Without the suggested line added, the provided test is looking for something that has no possibility of existing since bike.rings = [3,7] has to first be loaded into the object before it can have the chance to calculate total speeds.

**Comment by tannerwelsh** [comment]
@optomal7 well, not necessarily :) If you remember from the stage two tests, new bikes have rings of `[3,7]` _by default_. (Here's the test https://github.com/GuildCrafts/oop-practice/blob/master/bike-shop/test/stage2.test.js#L84)

So this test can pass, you'd just need to make sure your constructor function includes the appropriate setup.

**Comment by tannerwelsh** [comment]
Instead of changing the test itself, I modified the message: https://github.com/GuildCrafts/oop-practice/commit/4b3c8f19fcd73d69fbac30512b6615633cddf4bd

**Pull request closed without merging**
