### PR TITLE
Missing info

### PR DESCRIPTION
**Pull request by optomal7**

### CODE REVIEW

**Comment by optomal7** [comment]
ignore first commit on this PR. Was an early accidental push.

**Comment by tannerwelsh** [comment]
Closing this PR. @optomal7 please make PRs to the `master` branch on your fork, not to this repo. Thanks!

**Comment by optomal7** [comment]
That's fine, but you may want to review the stage 3 test file for bike-shop. The last test is literally impossible to pass unless you add the line I did. I don't think everyone will be clever enough to catch it on week 2 at LG.

**Comment by tannerwelsh** [comment]
Clarified test message https://github.com/GuildCrafts/oop-practice/commit/4b3c8f19fcd73d69fbac30512b6615633cddf4bd

**Pull request closed without merging**
